title: Santos Gallegos
name: Santos Gallegos
mail: santos_g@outlook.com
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
defaults:
  -
    scope:
      type: posts
    values:
      layout: post
      author:
        name: Santos Gallegos
        twitter: stsewd
      published: false
      section: blog
      social: true
      comments: true
