title: Santos Gallegos
name: Santos Gallegos
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
defaults:
  -
    scope:
      type: posts
    values:
      layout: post
      section: blog
